# Generated by Django 5.2.8 on 2025-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('destination_type', models.CharField(choices=[('safari', 'Safari'), ('beach', 'Beach'), ('city', 'City'), ('mountain', 'Mountain'), ('cultural', 'Cultural')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('average_cost_per_day', models.IntegerField(help_text='Average cost in KSh')),
                ('popular_activities', models.TextField(help_text='Comma-separated activities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
