# Generated by Django 4.2.7 on 2025-12-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('enable_mpesa', models.BooleanField(default=True, help_text='Master switch for M-Pesa payments')),
                ('enable_sponsorship', models.BooleanField(default=True, help_text="Enable 'Buy us a Coffee' / Sponsorship feature")),
                ('enable_subscriptions', models.BooleanField(default=False, help_text='Enable recurring subscription plans (Future use)')),
                ('mpesa_environment', models.CharField(choices=[('sandbox', 'Sandbox (Test)'), ('production', 'Production (Live)')], default='sandbox', help_text='Switch between Test and Live modes', max_length=20)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum allowed transaction amount in KSh', max_digits=10)),
                ('sponsorship_options', models.JSONField(default=list, help_text='List of preset amounts for sponsorship buttons (e.g., [100, 500, 1000])')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configuration',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='M-Pesa Receipt Number (e.g., QKH1...)', max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(help_text='Unique ID for the STK Push request', max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(help_text='Format: 2547...', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('sponsorship', 'Sponsorship/Donation'), ('itinerary', 'Itinerary Purchase'), ('subscription', 'Subscription')], max_length=20)),
                ('reference', models.CharField(help_text="Internal reference (e.g., Order ID or 'Sponsorship')", max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_cc4d34_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_c1fd68_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx')],
            },
        ),
    ]
