# Generated by Django 4.2.7 on 2025-12-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfiguration',
            name='enable_flutterwave',
            field=models.BooleanField(default=True, help_text='Enable Card/Global payments via Flutterwave'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='flutterwave_ref',
            field=models.CharField(blank=True, help_text='Flutterwave Transaction Reference (tx_ref)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_provider',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('flutterwave', 'Flutterwave (Card)')], default='mpesa', max_length=20),
        ),
    ]
