# Generated by Django 5.2.8 on 2025-11-16 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adults_count', models.IntegerField(default=2)),
                ('children_count', models.IntegerField(default=0)),
                ('travel_type', models.CharField(max_length=20)),
                ('total_budget', models.IntegerField(help_text='Total budget in KSh')),
                ('budget_category', models.CharField(max_length=20)),
                ('itinerary_data', models.JSONField(help_text='Full day-by-day itinerary from Gemini')),
                ('cost_breakdown', models.JSONField(help_text='Detailed cost breakdown')),
                ('is_saved', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(to='destinations.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WizardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('travel_start_date', models.DateField(blank=True, null=True)),
                ('travel_end_date', models.DateField(blank=True, null=True)),
                ('adults_count', models.IntegerField(default=2)),
                ('children_count', models.IntegerField(default=0)),
                ('travel_type', models.CharField(blank=True, max_length=20, null=True)),
                ('budget_amount', models.IntegerField(blank=True, help_text='Total budget in KSh', null=True)),
                ('budget_category', models.CharField(blank=True, max_length=20, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('current_step', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_destinations', models.ManyToManyField(blank=True, to='destinations.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
