# Generated by Django 5.2.8 on 2025-11-17 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier (e.g., 'budget', 'mid-range', 'luxury')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Budget-Friendly')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this budget tier includes')),
                ('min_budget_per_day', models.IntegerField(help_text='Minimum daily budget in KSh', validators=[django.core.validators.MinValueValidator(1000)])),
                ('max_budget_per_day', models.IntegerField(help_text='Maximum daily budget in KSh', validators=[django.core.validators.MinValueValidator(1000)])),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this budget category is available')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['sort_order', 'min_budget_per_day'],
            },
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier (e.g., 'wildlife', 'culture')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Wildlife & Safari')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this interest category')),
                ('icon', models.CharField(blank=True, help_text="Icon class or emoji (e.g., 'bi-binoculars', '🦁')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this interest is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interest Category',
                'verbose_name_plural': 'Interest Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_trip_duration', models.IntegerField(default=1, help_text='Minimum trip duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_trip_duration', models.IntegerField(default=30, help_text='Maximum trip duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_budget', models.IntegerField(default=10000, help_text='Minimum total budget in KSh', validators=[django.core.validators.MinValueValidator(1000)])),
                ('max_budget', models.IntegerField(default=500000, help_text='Maximum total budget in KSh', validators=[django.core.validators.MinValueValidator(1000)])),
                ('min_adults', models.IntegerField(default=1, help_text='Minimum number of adults', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_adults', models.IntegerField(default=20, help_text='Maximum number of adults', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_children', models.IntegerField(default=20, help_text='Maximum number of children', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_total_travelers', models.IntegerField(default=30, help_text='Maximum total travelers (adults + children)', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_destinations', models.IntegerField(default=10, help_text='Maximum destinations per trip', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_interests', models.IntegerField(default=10, help_text='Maximum interests per user', validators=[django.core.validators.MinValueValidator(1)])),
                ('enable_ai_generation', models.BooleanField(default=True, help_text='Enable AI-powered itinerary generation')),
                ('enable_weather_forecasts', models.BooleanField(default=True, help_text='Enable weather forecast integration')),
                ('enable_custom_destinations', models.BooleanField(default=True, help_text='Allow users to add custom destinations')),
                ('support_email', models.EmailField(default='info@safarismart.co.ke', help_text='Support email address', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Last updated by (username)', max_length=100)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier (e.g., 'solo', 'family')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Family Trip')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this travel type')),
                ('icon', models.CharField(blank=True, help_text="Icon class or emoji (e.g., 'bi-people', '👨\u200d👩\u200d👧\u200d👦')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this travel type is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Type',
                'verbose_name_plural': 'Travel Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_min', models.IntegerField(help_text='Minimum accommodation cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('accommodation_max', models.IntegerField(help_text='Maximum accommodation cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('activities_min', models.IntegerField(help_text='Minimum activities cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('activities_max', models.IntegerField(help_text='Maximum activities cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('meals_min', models.IntegerField(help_text='Minimum meals cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('meals_max', models.IntegerField(help_text='Maximum meals cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_min', models.IntegerField(help_text='Minimum transport cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_max', models.IntegerField(help_text='Maximum transport cost per day (KSh)', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about these estimates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.OneToOneField(help_text='Budget category for these estimates', on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='core.budgetcategory')),
            ],
            options={
                'verbose_name': 'Budget Estimate',
                'verbose_name_plural': 'Budget Estimates',
            },
        ),
    ]
