# Generated by Django 5.2.8 on 2025-11-17 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budgetcategory_interestcategory_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='admin_notification_email',
            field=models.EmailField(default='admin@safarismart.co.ke', help_text='Email for admin notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='announcement_link',
            field=models.URLField(blank=True, help_text='Optional link for announcement'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='announcement_link_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Text for announcement link', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='announcement_text',
            field=models.TextField(blank=True, help_text='Announcement text to display'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='announcement_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Alert')], default='info', help_text='Announcement banner style', max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='app_version',
            field=models.CharField(default='1.0.0', help_text='Current application version', max_length=20),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_analytics',
            field=models.BooleanField(default=True, help_text='Enable Google Analytics tracking'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications to users'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_error_reporting',
            field=models.BooleanField(default=True, help_text='Enable automatic error reporting'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_itinerary_saving',
            field=models.BooleanField(default=True, help_text='Allow users to save itineraries'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_itinerary_sharing',
            field=models.BooleanField(default=True, help_text='Allow users to share itineraries'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_rate_limiting',
            field=models.BooleanField(default=True, help_text='Enable rate limiting for API requests'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_user_registration',
            field=models.BooleanField(default=True, help_text='Allow new user registrations'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='gemini_api_rate_limit',
            field=models.IntegerField(default=60, help_text='Gemini API requests per minute limit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='last_deployment_date',
            field=models.DateTimeField(blank=True, help_text='Last deployment date', null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='maintenance_message',
            field=models.TextField(blank=True, default="We're currently performing maintenance. Please check back soon!", help_text='Message to display during maintenance'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode (site unavailable to users)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_itineraries_per_day',
            field=models.IntegerField(default=10, help_text='Maximum itineraries a user can generate per day', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_itineraries_per_hour',
            field=models.IntegerField(default=3, help_text='Maximum itineraries a user can generate per hour', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='meta_description',
            field=models.TextField(default='Plan your perfect Kenya safari, beach vacation & adventure with AI. Get personalized itineraries, weather forecasts & interactive maps.', help_text='Default meta description for SEO'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='show_announcement',
            field=models.BooleanField(default=False, help_text='Show announcement banner on homepage'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='site_name',
            field=models.CharField(default='SafariSmart Kenya', help_text='Site name for SEO', max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='site_tagline',
            field=models.CharField(default='AI-Powered Kenya Safari & Beach Trip Planner', help_text='Site tagline for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='weather_api_cache_hours',
            field=models.IntegerField(default=6, help_text='Hours to cache weather data', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
