# Generated by Django 5.2.8 on 2025-11-17 14:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfiguration_admin_notification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('gemini', 'Gemini AI'), ('weather', 'Weather API'), ('maps', 'Maps API'), ('other', 'Other')], db_index=True, help_text='API service name', max_length=50)),
                ('endpoint', models.CharField(blank=True, help_text='Specific endpoint or method called', max_length=200)),
                ('request_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was made')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('rate_limited', 'Rate Limited'), ('queued', 'Queued'), ('timeout', 'Timeout')], db_index=True, default='success', help_text='Request outcome', max_length=20)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens consumed (for AI APIs)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Estimated cost in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('error_message', models.TextField(blank=True, help_text='Error details if request failed')),
                ('user_id', models.IntegerField(blank=True, db_index=True, help_text='User who triggered the call', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Request IP address', null=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Request parameters (sanitized)')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response summary (sanitized)')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'ordering': ['-request_time'],
                'indexes': [models.Index(fields=['api_name', 'request_time'], name='core_apiusa_api_nam_b50c6f_idx'), models.Index(fields=['status', 'request_time'], name='core_apiusa_status_2845d4_idx'), models.Index(fields=['request_time'], name='core_apiusa_request_483f84_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(db_index=True, help_text='API service name', max_length=50)),
                ('period_type', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('month', 'Monthly')], db_index=True, help_text='Aggregation period', max_length=10)),
                ('period_start', models.DateTimeField(db_index=True, help_text='Period start time')),
                ('total_calls', models.IntegerField(default=0, help_text='Total API calls in period', validators=[django.core.validators.MinValueValidator(0)])),
                ('successful_calls', models.IntegerField(default=0, help_text='Successful calls', validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_calls', models.IntegerField(default=0, help_text='Failed calls', validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_limited_calls', models.IntegerField(default=0, help_text='Rate limited calls', validators=[django.core.validators.MinValueValidator(0)])),
                ('queued_calls', models.IntegerField(default=0, help_text='Queued calls', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tokens', models.BigIntegerField(default=0, help_text='Total tokens consumed', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Total cost in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average response time in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
            ],
            options={
                'verbose_name': 'API Usage Statistics',
                'verbose_name_plural': 'API Usage Statistics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['api_name', 'period_type', 'period_start'], name='core_apiusa_api_nam_768961_idx'), models.Index(fields=['period_start'], name='core_apiusa_period__75e9ef_idx')],
                'unique_together': {('api_name', 'period_type', 'period_start')},
            },
        ),
    ]
