# Generated by Django 5.2.8 on 2025-11-17 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apiusagelog_apiusagestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('brute_force_enabled', models.BooleanField(default=True, help_text='Protect against brute force login attacks', verbose_name='Enable Brute Force Protection')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Lock account after this many failed attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Maximum Login Attempts')),
                ('lockout_duration_minutes', models.IntegerField(default=30, help_text='How long to lock account after failed attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Lockout Duration (minutes)')),
                ('global_rate_limit_enabled', models.BooleanField(default=True, help_text='Limit requests per IP address', verbose_name='Enable Global Rate Limiting')),
                ('global_rate_limit_per_minute', models.IntegerField(default=100, help_text='Maximum requests per minute per IP', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='Global Rate Limit (per minute)')),
                ('api_rate_limit_per_minute', models.IntegerField(default=60, help_text='Maximum API requests per minute', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='API Rate Limit (per minute)')),
                ('api_rate_limit_per_hour', models.IntegerField(default=1000, help_text='Maximum API requests per hour', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='API Rate Limit (per hour)')),
                ('api_rate_limit_per_day', models.IntegerField(default=10000, help_text='Maximum API requests per day', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)], verbose_name='API Rate Limit (per day)')),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Automatically logout after this many minutes of inactivity', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Session Timeout (minutes)')),
                ('session_expire_on_close', models.BooleanField(default=False, help_text='End session when user closes browser', verbose_name='Expire Session on Browser Close')),
                ('require_https_cookies', models.BooleanField(default=True, help_text='Only send cookies over HTTPS (production only)', verbose_name='Require HTTPS for Cookies')),
                ('validate_session_ip', models.BooleanField(default=True, help_text='Detect session hijacking by validating IP', verbose_name='Validate Session IP Address')),
                ('validate_session_user_agent', models.BooleanField(default=True, help_text='Detect session hijacking by validating browser', verbose_name='Validate Session User Agent')),
                ('min_password_length', models.IntegerField(default=12, help_text='Minimum number of characters required', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(128)], verbose_name='Minimum Password Length')),
                ('require_uppercase', models.BooleanField(default=True, help_text='Password must contain uppercase letters (A-Z)', verbose_name='Require Uppercase Letters')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Password must contain lowercase letters (a-z)', verbose_name='Require Lowercase Letters')),
                ('require_numbers', models.BooleanField(default=True, help_text='Password must contain numbers (0-9)', verbose_name='Require Numbers')),
                ('require_special_chars', models.BooleanField(default=True, help_text='Password must contain special characters (!@#$%^&*)', verbose_name='Require Special Characters')),
                ('password_expiry_days', models.IntegerField(default=0, help_text='Force password change after N days (0 = never)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Password Expiry (days)')),
                ('admin_ip_whitelist_enabled', models.BooleanField(default=False, help_text='Restrict admin access to specific IP addresses', verbose_name='Enable Admin IP Whitelist')),
                ('admin_allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (e.g., 192.168.1.1, 10.0.0.1)', verbose_name='Admin Allowed IPs')),
                ('admin_session_timeout_minutes', models.IntegerField(default=15, help_text='Admin sessions timeout faster for security', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Admin Session Timeout (minutes)')),
                ('enable_hsts', models.BooleanField(default=True, help_text='HTTP Strict Transport Security (force HTTPS)', verbose_name='Enable HSTS')),
                ('hsts_max_age_seconds', models.IntegerField(default=31536000, help_text='How long browsers should remember to use HTTPS (1 year = 31536000)', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(63072000)], verbose_name='HSTS Max Age (seconds)')),
                ('enable_csp', models.BooleanField(default=True, help_text='Prevent XSS and injection attacks', verbose_name='Enable Content Security Policy')),
                ('enable_xss_protection', models.BooleanField(default=True, help_text='Enable browser XSS filter', verbose_name='Enable XSS Protection')),
                ('enable_clickjacking_protection', models.BooleanField(default=True, help_text='Prevent site from being embedded in iframes', verbose_name='Enable Clickjacking Protection')),
                ('enable_security_logging', models.BooleanField(default=True, help_text='Log all security events', verbose_name='Enable Security Logging')),
                ('enable_failed_login_alerts', models.BooleanField(default=True, help_text='Send alerts for failed login attempts', verbose_name='Enable Failed Login Alerts')),
                ('failed_login_alert_threshold', models.IntegerField(default=3, help_text='Send alert after this many failed attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Failed Login Alert Threshold')),
                ('enable_suspicious_activity_alerts', models.BooleanField(default=True, help_text='Alert on suspicious patterns (SQL injection, XSS, etc.)', verbose_name='Enable Suspicious Activity Alerts')),
                ('alert_email', models.EmailField(blank=True, help_text='Email address for security alerts', max_length=254, verbose_name='Security Alert Email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('updated_by', models.CharField(blank=True, max_length=150, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('successful_login', 'Successful Login'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('session_hijack_attempt', 'Session Hijack Attempt'), ('admin_access', 'Admin Access'), ('config_change', 'Configuration Change'), ('password_change', 'Password Change'), ('security_alert', 'Security Alert')], db_index=True, max_length=50, verbose_name='Event Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='Severity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='User')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Additional Details')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolved_by', models.CharField(blank=True, max_length=150, verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_securi_event_t_72c930_idx'), models.Index(fields=['severity', 'timestamp'], name='core_securi_severit_382860_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_securi_ip_addr_a2d011_idx')],
            },
        ),
    ]
