# Generated by Django 5.2.8 on 2025-11-19 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_securitysettings_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable chat feature for custom trip planning')),
                ('use_ai_for_complex', models.BooleanField(default=True, help_text='Use AI (Gemini) for complex user queries')),
                ('welcome_message', models.TextField(default="Hi! I'm your Safari planning assistant. Tell me about your dream trip to Kenya! 🦁", help_text='First message users see when opening chat')),
                ('destination_question', models.TextField(default='Where would you like to go in Kenya?', help_text='Question asking for destination')),
                ('duration_question', models.TextField(default='How many days do you have for this trip?', help_text='Question asking for trip duration')),
                ('budget_question', models.TextField(default="What's your budget level?", help_text='Question asking for budget tier')),
                ('interests_question', models.TextField(default='What interests you most?', help_text='Question asking for travel interests')),
                ('completion_message', models.TextField(default='Perfect! Let me create your personalized itinerary... ✨', help_text='Message shown when generating itinerary')),
                ('error_message', models.TextField(default="Sorry, I didn't quite understand that. Could you rephrase?", help_text="Message when bot doesn't understand input")),
                ('ai_complexity_threshold', models.IntegerField(default=10, help_text='Minimum word count to trigger AI (lower = more AI usage, higher = more simple chat)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('max_chat_turns', models.IntegerField(default=10, help_text='Maximum conversation turns before forcing completion', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Configuration',
                'verbose_name_plural': 'Chat Configuration',
            },
        ),
    ]
