# Generated by Django 5.2.8 on 2025-11-19 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Page title (e.g., 'About Us', 'Privacy Policy')", max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from title)', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Page content (HTML supported)', validators=[django.core.validators.MinLengthValidator(50)])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (160 characters max)', max_length=160)),
                ('is_published', models.BooleanField(default=True, help_text='Make page publicly visible')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show link in footer menu')),
                ('footer_order', models.IntegerField(default=0, help_text='Order in footer menu (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['footer_order', 'title'],
            },
        ),
    ]
