# Generated by Django 5.2.8 on 2025-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@safarismart.co.ke', help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (e.g., +254 796 915 745)', max_length=20)),
                ('location', models.CharField(default='Nairobi, Kenya', help_text='Business location', max_length=100)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website URL')),
                ('portfolio_text', models.CharField(default='Explore my work', help_text='Text for portfolio link', max_length=50)),
                ('about_text', models.TextField(default='Your intelligent trip planning platform for Kenya. Discover safaris, beaches, and unforgettable adventures.', help_text='Short description for footer')),
                ('creator_name', models.CharField(default='Vincent Owuor', help_text='Creator/developer name', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
