# Generated by Django 5.2.8 on 2025-11-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('trip_created', 'Trip Created'), ('trip_shared', 'Trip Shared'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification'), ('newsletter', 'Newsletter'), ('booking_confirmation', 'Booking Confirmation'), ('custom', 'Custom Email')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content with template variables')),
                ('text_content', models.TextField(blank=True, help_text='Plain text email content')),
                ('available_variables', models.TextField(blank=True, default='Common variables: {{ user.first_name }}, {{ user.username }}, {{ user.email }}', help_text='Available template variables (for reference)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['email_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
