# Generated by Django 5.2.8 on 2025-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.EmailField(default='SafariSmart Kenya <noreply@safarismart.co.ke>', help_text='Default email address for outgoing emails', max_length=254)),
                ('support_email', models.EmailField(default='support@safarismart.co.ke', help_text='Support email address for customer inquiries', max_length=254)),
                ('booking_email', models.EmailField(default='bookings@safarismart.co.ke', help_text='Email address for booking confirmations', max_length=254)),
                ('marketing_email', models.EmailField(default='hello@safarismart.co.ke', help_text='Email address for marketing emails', max_length=254)),
                ('company_name', models.CharField(default='SafariSmart Kenya', help_text='Company name to display in emails', max_length=100)),
                ('company_tagline', models.CharField(default='Your Gateway to Amazing Adventures', help_text='Company tagline for email footers', max_length=200)),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP server host (leave blank to use .env settings)', max_length=100)),
                ('smtp_port', models.IntegerField(blank=True, help_text='SMTP server port (leave blank to use .env settings)', null=True)),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP username (leave blank to use .env settings)', max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP connection')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable/disable all email notifications')),
                ('enable_welcome_emails', models.BooleanField(default=True, help_text='Send welcome emails to new users')),
                ('enable_trip_notifications', models.BooleanField(default=True, help_text='Send notifications when users create trips')),
                ('enable_marketing_emails', models.BooleanField(default=False, help_text='Enable marketing/newsletter emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
