# Generated by Django 5.2.8 on 2025-11-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_emailsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('trips_created', models.IntegerField(default=0)),
                ('mobile_percentage', models.FloatField(default=0.0)),
                ('top_browser', models.CharField(blank=True, max_length=50)),
                ('top_country', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(help_text='Hashed session identifier', max_length=64)),
                ('path', models.CharField(help_text='URL path (no query params)', max_length=200)),
                ('page_category', models.CharField(help_text='landing, destinations, trips, etc.', max_length=50)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser_family', models.CharField(blank=True, help_text='Chrome, Firefox, Safari', max_length=50)),
                ('country_code', models.CharField(blank=True, help_text='KE, US, UK, etc.', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'page_category'], name='core_anonym_timesta_488e09_idx'), models.Index(fields=['anonymous_id'], name='core_anonym_anonymo_5b2346_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='For anonymous users', max_length=40)),
                ('consent_type', models.CharField(choices=[('essential', 'Essential Cookies (Required)'), ('analytics', 'Analytics Cookies (Optional)'), ('marketing', 'Marketing Cookies (Optional)'), ('personalization', 'Personalization (Optional)')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'consent_type'], name='core_consen_user_id_815efd_idx'), models.Index(fields=['session_key', 'consent_type'], name='core_consen_session_a2c825_idx')],
                'unique_together': {('user', 'session_key', 'consent_type')},
            },
        ),
    ]
